
EpicGames_RTC_RemoveNotifyDisconnected(NotifyDisconnected)
EpicGames_RTC_RemoveNotifyParticipantStatusChanged(ParticipantStatusChanged)
EpicGames_RTC_RemoveNotifyRoomStatisticsUpdated(RoomStatisticsUpdated)
//EpicGames_RTCAudio_RemoveNotifyAudioBeforeRender(AudioBeforeRender)//Unnecesary of this example
//EpicGames_RTCAudio_RemoveNotifyAudioBeforeSend(AudioBeforeSend)//Unnecesary of this example
EpicGames_RTCAudio_RemoveNotifyAudioDevicesChanged(AudioDevicesChanged)
EpicGames_RTCAudio_RemoveNotifyAudioInputState(AudioInputState)
EpicGames_RTCAudio_RemoveNotifyAudioOutputState(AudioOutputState)
EpicGames_RTCAudio_RemoveNotifyParticipantUpdated(Audio_ParticipantUpdated)
EpicGames_RTCData_RemoveNotifyDataReceived(DataReceived)
EpicGames_RTCData_RemoveNotifyParticipantUpdated(Data_ParticipantUpdated)
