
eos_rtc_remove_notify_disconnected(NotifyDisconnected)
eos_rtc_remove_notify_participant_status_changed(ParticipantStatusChanged)
eos_rtc_remove_notify_room_statistics_updated(RoomStatisticsUpdated)
//eos_rtc_audio_remove_notify_audio_before_render(AudioBeforeRender)//Unnecesary of this example
//eos_rtc_audio_remove_notify_audio_before_send(AudioBeforeSend)//Unnecesary of this example
eos_rtc_audio_remove_notify_audio_devices_changed(AudioDevicesChanged)
eos_rtc_audio_remove_notify_audio_input_state(AudioInputState)
eos_rtc_audio_remove_notify_audio_output_state(AudioOutputState)
eos_rtc_audio_remove_notify_participant_updated(Audio_ParticipantUpdated)
eos_rtc_data_remove_notify_data_received(DataReceived)
eos_rtc_data_remove_notify_participant_updated(Data_ParticipantUpdated)
