
NotifyDisconnected = eos_rtc_add_notify_disconnected(global.product_user_id,RoomName)
ParticipantStatusChanged = eos_rtc_add_notify_participant_status_changed(global.product_user_id,RoomName)
RoomStatisticsUpdated = eos_rtc_add_notify_room_statistics_updated(global.product_user_id,RoomName)
//AudioBeforeRender = eos_rtc_audio_add_notify_audio_before_render(global.product_user_id,RoomName,true)//Unnecesary of this example
//AudioBeforeSend = eos_rtc_audio_add_notify_audio_before_send(global.product_user_id,RoomName)//Unnecesary of this example
AudioDevicesChanged = eos_rtc_audio_add_notify_audio_devices_changed()
AudioInputState = eos_rtc_audio_add_notify_audio_input_state(global.product_user_id,RoomName)
AudioOutputState = eos_rtc_audio_add_notify_audio_output_state(global.product_user_id,RoomName)
Audio_ParticipantUpdated = eos_rtc_audio_add_notify_participant_updated(global.product_user_id,RoomName)
DataReceived = eos_rtc_data_add_notify_data_received(global.product_user_id,RoomName)
Data_ParticipantUpdated = eos_rtc_data_add_notify_participant_updated(global.product_user_id,RoomName)

