
EpicGames_Lobby_RemoveNotifyJoinLobbyAccepted(notifyJoinLobbyAccepted)
EpicGames_Lobby_RemoveNotifyLeaveLobbyRequested(notifyLeaveLobbyRequested)
EpicGames_Lobby_RemoveNotifyLobbyInviteAccepted(notifyLobbyInviteAccepted)
EpicGames_Lobby_RemoveNotifyLobbyInviteReceived(notifyLobbyInviteReceived)
EpicGames_Lobby_RemoveNotifyLobbyInviteRejected(notifyLobbyInviteRejected)
EpicGames_Lobby_RemoveNotifyLobbyMemberStatusReceived(notifyLobbyMemberStatusReceived)
EpicGames_Lobby_RemoveNotifyLobbyMemberUpdateReceived(notifyLobbyMemberUpdateReceived)
EpicGames_Lobby_RemoveNotifyLobbyUpdateReceived(notifyLobbyUpdateReceived)
EpicGames_Lobby_RemoveNotifyRTCRoomConnectionChanged(notifyRTCRoomConnectionChanged)
EpicGames_Lobby_RemoveNotifySendLobbyNativeInviteRequested(notifySendLobbyNativeInviteRequested)

