
eos_lobby_remove_notify_join_lobby_accepted(notifyJoinLobbyAccepted)
eos_lobby_remove_notify_leave_lobby_requested(notifyLeaveLobbyRequested)
eos_lobby_remove_notify_lobby_invite_accepted(notifyLobbyInviteAccepted)
eos_lobby_remove_notify_lobby_invite_received(notifyLobbyInviteReceived)
eos_lobby_remove_notify_lobby_invite_rejected(notifyLobbyInviteRejected)
eos_lobby_remove_notify_lobby_member_status_received(notifyLobbyMemberStatusReceived)
eos_lobby_remove_notify_lobby_member_update_received(notifyLobbyMemberUpdateReceived)
eos_lobby_remove_notify_lobby_update_received(notifyLobbyUpdateReceived)
eos_lobby_remove_notify_rtc_room_connection_changed(notifyRTCRoomConnectionChanged)
eos_lobby_remove_notify_send_lobby_native_invite_requested(notifySendLobbyNativeInviteRequested)

if(LobbyId != "")
	eos_lobby_leave_lobby(LobbyId,userID)
