
event_inherited();

text = "Lobby"

LobbyId = ""

notifyJoinLobbyAccepted = EpicGames_Lobby_AddNotifyJoinLobbyAccepted()
notifyLeaveLobbyRequested = EpicGames_Lobby_AddNotifyLeaveLobbyRequested()
notifyLobbyInviteAccepted = EpicGames_Lobby_AddNotifyLobbyInviteAccepted()
notifyLobbyInviteReceived = EpicGames_Lobby_AddNotifyLobbyInviteReceived()
notifyLobbyInviteRejected = EpicGames_Lobby_AddNotifyLobbyInviteRejected()
notifyLobbyMemberStatusReceived = EpicGames_Lobby_AddNotifyLobbyMemberStatusReceived()
notifyLobbyMemberUpdateReceived = EpicGames_Lobby_AddNotifyLobbyMemberUpdateReceived()
notifyLobbyUpdateReceived = EpicGames_Lobby_AddNotifyLobbyUpdateReceived()
notifyRTCRoomConnectionChanged = EpicGames_Lobby_AddNotifyRTCRoomConnectionChanged()
notifySendLobbyNativeInviteRequested = EpicGames_Lobby_AddNotifySendLobbyNativeInviteRequested()
