
eos_sessions_remove_notify_join_session_accepted(notifyJoinSessionAccepted)
eos_sessions_remove_notify_leave_session_requested(notifyLeaveSessionRequested)
eos_sessions_remove_notify_send_session_native_invite_requested(notifySendSessionNativeInviteRequested)
eos_sessions_remove_notify_session_invite_accepted(notifySessionInviteAccepted)
eos_sessions_remove_notify_session_invite_received(notifySessionInviteReceived)
eos_sessions_remove_notify_session_invite_rejected(notifySessionInviteRejected)
