
EpicGames_Sessions_RemoveNotifyJoinSessionAccepted(notifyJoinSessionAccepted)
EpicGames_Sessions_RemoveNotifyLeaveSessionRequested(notifyLeaveSessionRequested)
EpicGames_Sessions_RemoveNotifySendSessionNativeInviteRequested(notifySendSessionNativeInviteRequested)
EpicGames_Sessions_RemoveNotifySessionInviteAccepted(notifySessionInviteAccepted)
EpicGames_Sessions_RemoveNotifySessionInviteReceived(notifySessionInviteReceived)
EpicGames_Sessions_RemoveNotifySessionInviteRejected(notifySessionInviteRejected)
