
event_inherited();

text = "Sessions"

notifyJoinSessionAccepted = EpicGames_Sessions_AddNotifyJoinSessionAccepted()
notifyLeaveSessionRequested = EpicGames_Sessions_AddNotifyLeaveSessionRequested()
notifySendSessionNativeInviteRequested = EpicGames_Sessions_AddNotifySendSessionNativeInviteRequested()
notifySessionInviteAccepted = EpicGames_Sessions_AddNotifySessionInviteAccepted()
notifySessionInviteReceived = EpicGames_Sessions_AddNotifySessionInviteReceived()
notifySessionInviteRejected = EpicGames_Sessions_AddNotifySessionInviteRejected()

