

EpicGames_Auth_RemoveNotifyLoginStatusChanged(NotifyID_Auth_LoginStatusChanged)
EpicGames_Connect_RemoveNotifyAuthExpiration(NotifyID_Connect_AuthExpiration)
EpicGames_Connect_RemoveNotifyLoginStatusChanged(NotifyID_Connect_LoginStatusChanged)
EpicGames_Friends_RemoveNotifyFriendsUpdate(NotifyID_Friends)
EpicGames_Achievements_RemoveNotifyAchievementsUnlocked(NotifyID_Achievements_UnlockedV2)
EpicGames_UI_RemoveNotifyDisplaySettingsUpdated(NotifyID_UI_DisplaySettingsUpdated)

EpicGames_Shutdown()
