

eos_auth_remove_notify_login_status_changed(NotifyID_Auth_LoginStatusChanged)
eos_connect_remove_notify_auth_expiration(NotifyID_Connect_AuthExpiration)
eos_connect_remove_notify_login_status_changed(NotifyID_Connect_LoginStatusChanged)
eos_friends_remove_notify_friends_update(NotifyID_Friends)
eos_achievements_remove_notify_achievements_unlocked(NotifyID_Achievements_UnlockedV2)
eos_ui_remove_notify_display_settings_updated(NotifyID_UI_DisplaySettingsUpdated)

eos_shutdown()
