

eos_auth_remove_notify_login_status_changed(notify_login_status_changed)
eos_connect_remove_notify_auth_expiration(notify_auth_expiration)
eos_connect_remove_notify_login_status_changed(notify_login_status_changed)
eos_friends_remove_notify_friends_update(notify_friends_update)
eos_achievements_remove_notify_achievements_unlocked(notify_achievements_unlocked_v2)
eos_ui_remove_notify_display_settings_updated(notify_display_settings_updated)

eos_api_shutdown()
