

eos_auth_remove_notify_login_status_changed(notify_auth_login_status_changed)
eos_connect_remove_notify_auth_expiration(notify_auth_expiration)
eos_connect_remove_notify_login_status_changed(notify_connect_login_status_changed)
eos_friends_remove_notify_friends_update(notify_friends_update)
eos_achievements_remove_notify_achievements_unlocked(notify_achievements_unlocked_v2)
eos_ui_remove_notify_display_settings_updated(notify_display_settings_updated)
eos_presence_remove_notify_join_game_accepted(notify_presence_join_game_accepted)
eos_custominvites_remove_notify_send_custom_native_invite_requested(notify_custominvites_send_native_invite_requested)

eos_api_shutdown()
