// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__EpicOnlineServices_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

GMEXPORT double __EXT_NATIVE__eos_test();
GMEXPORT char* __EXT_NATIVE__eos_api_last_error();
GMEXPORT double __EXT_NATIVE__eos_api_is_initialized();
GMEXPORT double __EXT_NATIVE__eos_api_initialize(char* product_name, char* product_version, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_api_shutdown(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_api_get_version();
GMEXPORT char* __EXT_NATIVE__eos_api_result_to_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_api_result_is_operation_complete(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_api_application_status_to_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_api_network_status_to_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_api_epic_account_id_is_valid(char* account_id);
GMEXPORT double __EXT_NATIVE__eos_api_product_user_id_is_valid(char* product_user_id);
GMEXPORT double __EXT_NATIVE__eos_platform_is_created();
GMEXPORT double __EXT_NATIVE__eos_platform_create(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_platform_release();
GMEXPORT double __EXT_NATIVE__eos_platform_tick();
GMEXPORT double __EXT_NATIVE__eos_platform_check_for_launcher_and_restart(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_platform_set_network_status(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_logging_set_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_logging_clear_callback();
GMEXPORT double __EXT_NATIVE__eos_logging_set_log_level(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_login(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_logout(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_link_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_delete_persistent_auth(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_get_logged_in_accounts_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_auth_get_logged_in_account_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_get_login_status(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_copy_id_token(char* local_user_id, char* target_account_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_copy_user_auth_token(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_query_id_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_verify_id_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_verify_user_auth(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_add_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_remove_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_login(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_create_user(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_link_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_unlink_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_create_device_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_delete_device_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_transfer_device_id_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_logout(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_get_logged_in_users_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_connect_get_logged_in_user_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_get_login_status(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_id_token(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_info(char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_external_account_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_external_account_by_account_type(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_external_account_by_account_id(char* target_user_id, char* account_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_connect_get_product_user_id_mapping(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_connect_get_external_account_mapping(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_verify_id_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_query_external_account_mappings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_query_product_user_id_mappings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_add_notify_auth_expiration(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_remove_notify_auth_expiration(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_add_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_remove_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_query_friends(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_get_friends_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_friends_get_friend_at_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_get_status(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_add_notify_friends_update(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_remove_notify_friends_update(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_query_user_info(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_user_info(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_get_local_platform_type(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_user_info_copy_best_display_name(char* local_user_id, char* target_user_id);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_external_user_info_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_external_user_info_by_account_type(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_external_user_info_by_account_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_ingest_stat(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_query_stats(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_get_stats_count(char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_copy_stat_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_copy_stat_by_name(char* target_user_id, char* name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_show_friends(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_show_native_profile(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_acknowledge_event_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_set_display_preference(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_report_input_state(double button_down, double button_up, double button_left, double button_right, double button_accept, double button_cancel);
GMEXPORT double __EXT_NATIVE__eos_ui_add_notify_display_settings_updated(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_remove_notify_display_settings_updated(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_metrics_begin_player_session(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_metrics_end_player_session(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_reports_send_player_behavior_report(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_query_active_player_sanctions(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_get_player_sanction_count(char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_copy_player_sanction_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_create_player_sanction_appeal(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_query_definitions(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_query_player_achievements(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_get_achievement_definition_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_get_player_achievement_count(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_achievement_definition_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_achievement_definition_v2_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_achievement_definition_by_id(char* achievement_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_player_achievement_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_player_achievement_by_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_unlock_achievements(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_add_notify_achievements_unlocked_v2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_remove_notify_achievements_unlocked(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_query_definitions(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_query_ranks(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_query_user_scores(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_get_definition_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_get_record_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_get_user_score_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_definition_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_definition_by_id(char* leaderboard_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_record_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_record_by_user_id(char* user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_user_score_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_query_presence(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_has_presence(char* local_user_id, char* target_user_id);
GMEXPORT double __EXT_NATIVE__eos_presence_copy_presence(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_create_presence_modification(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_set_status(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_set_raw_rich_text(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_set_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_delete_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_set_presence(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_add_notify_on_presence_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_remove_notify_on_presence_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_add_notify_join_game_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_remove_notify_join_game_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_create_session_modification(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_update_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_destroy_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_start_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_end_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_join_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_register_players(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_unregister_players(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_create_session_search(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_set_session_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_set_target_user_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_find(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_copy_search_result_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_details_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_copy_active_session_handle(char* session_name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_active_session_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_active_session_copy_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_copy_session_handle_by_invite_id(char* invite_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_copy_session_handle_by_ui_event_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_details_copy_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_session_invite_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_session_invite_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_session_invite_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_session_invite_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_join_session_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_join_session_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_create_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_destroy_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_join_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_leave_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_update_lobby_modification(char* lobby_id, char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_update_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_permission_level(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_max_members(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_bucket_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_invites_allowed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_add_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_remove_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_add_member_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_remove_member_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_promote_member(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_kick_member(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_create_lobby_search(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_lobby_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_target_user_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_parameter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_remove_parameter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_max_results(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_find(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_get_search_result_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_copy_search_result_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_copy_lobby_details_handle(char* lobby_id, char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_copy_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_get_member_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_lobby_details_get_member_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_lobby_details_get_lobby_owner(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_update_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_update_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_member_update_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_member_update_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_member_status_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_member_status_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_join_lobby_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_join_lobby_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_leave_lobby_requested(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_leave_lobby_requested(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_send_lobby_native_invite_requested(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_send_lobby_native_invite_requested(char* __arg_buffer, double __arg_buffer_length);

