// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__EpicOnlineServices_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

// Internal function used for queueing buffers to native code
GMEXPORT double __EXT_NATIVE__EpicOnlineServices_queue_buffer(char* __arg_buffer, double __arg_buffer_length);

GMEXPORT double __EXT_NATIVE__eos_test();
GMEXPORT char* __EXT_NATIVE__eos_api_last_error();
GMEXPORT double __EXT_NATIVE__eos_api_is_initialized();
GMEXPORT double __EXT_NATIVE__eos_api_initialize(char* product_name, char* product_version, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_api_shutdown(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_api_get_version();
GMEXPORT char* __EXT_NATIVE__eos_api_result_to_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_api_result_is_operation_complete(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_api_application_status_to_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_api_network_status_to_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_api_epic_account_id_is_valid(char* account_id);
GMEXPORT double __EXT_NATIVE__eos_api_product_user_id_is_valid(char* product_user_id);
GMEXPORT double __EXT_NATIVE__eos_platform_is_created();
GMEXPORT double __EXT_NATIVE__eos_platform_create(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_platform_release();
GMEXPORT double __EXT_NATIVE__eos_platform_tick();
GMEXPORT double __EXT_NATIVE__eos_platform_check_for_launcher_and_restart(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_platform_set_network_status(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_logging_set_callback(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_logging_clear_callback();
GMEXPORT double __EXT_NATIVE__eos_logging_set_log_level(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_login(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_logout(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_link_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_delete_persistent_auth(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_get_logged_in_accounts_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_auth_get_logged_in_account_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_get_login_status(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_copy_id_token(char* local_user_id, char* target_account_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_copy_user_auth_token(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_query_id_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_verify_id_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_verify_user_auth(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_add_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_auth_remove_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_login(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_create_user(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_link_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_unlink_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_create_device_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_delete_device_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_transfer_device_id_account(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_logout(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_get_logged_in_users_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_connect_get_logged_in_user_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_get_login_status(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_id_token(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_info(char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_external_account_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_external_account_by_account_type(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_copy_product_user_external_account_by_account_id(char* target_user_id, char* account_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_connect_get_product_user_id_mapping(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_connect_get_external_account_mapping(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_verify_id_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_query_external_account_mappings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_query_product_user_id_mappings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_add_notify_auth_expiration(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_remove_notify_auth_expiration(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_add_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_connect_remove_notify_login_status_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_query_friends(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_get_friends_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_friends_get_friend_at_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_get_status(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_add_notify_friends_update(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_friends_remove_notify_friends_update(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_query_user_info(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_user_info(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_get_local_platform_type(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_user_info_copy_best_display_name(char* local_user_id, char* target_user_id);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_external_user_info_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_external_user_info_by_account_type(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_user_info_copy_external_user_info_by_account_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_ingest_stat(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_query_stats(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_get_stats_count(char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_copy_stat_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_stats_copy_stat_by_name(char* target_user_id, char* name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_show_friends(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_show_native_profile(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_acknowledge_event_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_set_display_preference(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_report_input_state(double button_down, double button_up, double button_left, double button_right, double button_accept, double button_cancel);
GMEXPORT double __EXT_NATIVE__eos_ui_add_notify_display_settings_updated(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_remove_notify_display_settings_updated(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_hide_friends(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_get_friends_visible(char* local_user_id);
GMEXPORT double __EXT_NATIVE__eos_ui_get_friends_exclusive_input(char* local_user_id);
GMEXPORT double __EXT_NATIVE__eos_ui_pause_social_overlay(double is_paused, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_is_social_overlay_paused();
GMEXPORT double __EXT_NATIVE__eos_ui_get_notification_location_preference(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_show_block_player(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ui_show_report_player(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_metrics_begin_player_session(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_metrics_end_player_session(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_progression_snapshot_begin_snapshot(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_progression_snapshot_add_progression(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_progression_snapshot_end_snapshot(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_progression_snapshot_submit_snapshot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_progression_snapshot_delete_snapshot(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_reports_send_player_behavior_report(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_query_active_player_sanctions(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_get_player_sanction_count(char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_copy_player_sanction_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sanctions_create_player_sanction_appeal(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_query_definitions(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_query_player_achievements(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_get_achievement_definition_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_get_player_achievement_count(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_achievement_definition_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_achievement_definition_v2_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_achievement_definition_by_id(char* achievement_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_player_achievement_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_copy_player_achievement_by_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_unlock_achievements(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_add_notify_achievements_unlocked_v2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_achievements_remove_notify_achievements_unlocked(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_query_definitions(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_query_ranks(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_query_user_scores(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_get_definition_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_get_record_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_get_user_score_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_definition_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_definition_by_id(char* leaderboard_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_record_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_record_by_user_id(char* user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_leaderboards_copy_user_score_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_query_presence(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_has_presence(char* local_user_id, char* target_user_id);
GMEXPORT double __EXT_NATIVE__eos_presence_copy_presence(char* local_user_id, char* target_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_create_presence_modification(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_set_status(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_set_raw_rich_text(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_set_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_modification_delete_data(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_set_presence(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_add_notify_on_presence_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_remove_notify_on_presence_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_add_notify_join_game_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_presence_remove_notify_join_game_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_create_session_modification(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_update_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_destroy_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_start_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_end_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_join_session(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_register_players(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_unregister_players(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_create_session_search(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_set_session_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_set_target_user_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_find(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_copy_search_result_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_details_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_copy_active_session_handle(char* session_name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_active_session_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_active_session_copy_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_copy_session_handle_by_invite_id(char* invite_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_copy_session_handle_by_ui_event_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_details_copy_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_session_invite_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_session_invite_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_session_invite_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_session_invite_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_join_session_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_join_session_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_set_bucket_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_set_host_address(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_set_permission_level(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_set_join_in_progress_allowed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_set_max_players(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_set_invites_allowed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_add_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_modification_remove_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_details_get_session_attribute_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_details_copy_session_attribute_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_details_copy_session_attribute_by_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_active_session_get_registered_player_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_sessions_active_session_get_registered_player_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_send_invite(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_reject_invite(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_query_invites(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_get_invite_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_sessions_get_invite_id_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_set_parameter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_remove_parameter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_session_search_get_search_result_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_session_invite_rejected(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_session_invite_rejected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_leave_session_requested(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_leave_session_requested(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_add_notify_send_session_native_invite_requested(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_sessions_remove_notify_send_session_native_invite_requested(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_create_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_destroy_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_join_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_leave_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_update_lobby_modification(char* lobby_id, char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_update_lobby(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_permission_level(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_max_members(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_bucket_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_set_invites_allowed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_add_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_remove_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_add_member_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_modification_remove_member_attribute(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_promote_member(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_kick_member(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_create_lobby_search(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_lobby_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_target_user_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_parameter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_remove_parameter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_set_max_results(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_find(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_get_search_result_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_lobby_search_copy_search_result_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_copy_lobby_details_handle(char* lobby_id, char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_copy_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_get_member_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_lobby_details_get_member_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_lobby_details_get_lobby_owner(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_update_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_update_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_member_update_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_member_update_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_member_status_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_member_status_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_join_lobby_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_join_lobby_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_leave_lobby_requested(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_leave_lobby_requested(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_send_lobby_native_invite_requested(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_send_lobby_native_invite_requested(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_get_attribute_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_copy_attribute_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_copy_attribute_by_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_get_member_attribute_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_copy_member_attribute_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_copy_member_attribute_by_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_details_copy_member_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_join_lobby_by_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_hard_mute_member(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_send_invite(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_reject_invite(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_query_invites(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_get_invite_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_lobby_get_invite_id_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_invite_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_invite_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_invite_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_invite_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_add_notify_lobby_invite_rejected(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_lobby_remove_notify_lobby_invite_rejected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_send_packet(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_get_next_received_packet_size(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_receive_packet(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_accept_connection(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_close_connection(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_close_connections(char* local_user_id, char* socket_name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_query_nat_type(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_get_nat_type(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_set_relay_control(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_get_relay_control(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_set_port_range(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_get_port_range(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_set_packet_queue_size(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_get_packet_queue_info(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_clear_packet_queue(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_add_notify_peer_connection_request(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_remove_notify_peer_connection_request(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_add_notify_peer_connection_established(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_remove_notify_peer_connection_established(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_add_notify_peer_connection_interrupted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_remove_notify_peer_connection_interrupted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_add_notify_peer_connection_closed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_remove_notify_peer_connection_closed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_add_notify_incoming_packet_queue_full(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_p2p_remove_notify_incoming_packet_queue_full(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_query_file(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_query_file_list(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_get_file_metadata_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_copy_file_metadata_at_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_copy_file_metadata_by_filename(char* local_user_id, char* filename, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_duplicate_file(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_delete_file(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_read_file(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_write_file(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_playerdatastorage_delete_cache(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_titlestorage_query_file(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_titlestorage_query_file_list(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_titlestorage_get_file_metadata_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_titlestorage_copy_file_metadata_at_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_titlestorage_copy_file_metadata_by_filename(char* local_user_id, char* filename, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_titlestorage_read_file(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_titlestorage_delete_cache(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_query_ownership(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_query_ownership_by_sandbox_ids(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_query_ownership_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_query_entitlements(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_query_entitlement_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_query_offers(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_checkout(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_redeem_entitlements(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_item_ownership_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_item_ownership_at_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_sandbox_ownership_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_sandbox_ownership_at_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_entitlements_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_entitlements_by_name_count(char* local_user_id, char* entitlement_name, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_entitlement_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_entitlement_by_name_and_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_entitlement_by_id(char* local_user_id, char* entitlement_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_last_redeemed_entitlements_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_ecom_copy_last_redeemed_entitlement_by_index(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_offer_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_offer_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_offer_by_id(char* local_user_id, char* offer_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_offer_item_count(char* local_user_id, char* offer_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_offer_item_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_item_by_id(char* local_user_id, char* item_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_offer_image_info_count(char* local_user_id, char* offer_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_offer_image_info_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_item_image_info_count(char* local_user_id, char* item_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_item_image_info_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_item_release_count(char* local_user_id, char* item_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_item_release_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_get_transaction_count(char* local_user_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_transaction_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_copy_transaction_by_id(char* local_user_id, char* transaction_id, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__eos_ecom_transaction_get_transaction_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_transaction_get_entitlements_count(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_transaction_copy_entitlement_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_ecom_transaction_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_set_custom_invite(char* local_user_id, char* payload);
GMEXPORT double __EXT_NATIVE__eos_custominvites_send_custom_invite(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_finalize_invite(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_send_request_to_join(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_accept_request_to_join(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_reject_request_to_join(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_custom_invite_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_custom_invite_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_custom_invite_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_custom_invite_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_custom_invite_rejected(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_custom_invite_rejected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_request_to_join_response_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_request_to_join_response_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_request_to_join_received(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_request_to_join_received(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_send_custom_native_invite_requested(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_send_custom_native_invite_requested(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_request_to_join_accepted(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_request_to_join_accepted(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_add_notify_request_to_join_rejected(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_custominvites_remove_notify_request_to_join_rejected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_join_room(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_leave_room(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_block_participant(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_set_setting(char* setting_name, char* setting_value);
GMEXPORT double __EXT_NATIVE__eos_rtc_set_room_setting(char* local_user_id, char* room_name, char* setting_name, char* setting_value);
GMEXPORT double __EXT_NATIVE__eos_rtc_add_notify_disconnected(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_remove_notify_disconnected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_add_notify_participant_status_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_remove_notify_participant_status_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_add_notify_room_statistics_updated(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_remove_notify_room_statistics_updated(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_update_sending(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_update_receiving(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_update_sending_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_update_receiving_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_update_participant_volume(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_get_input_devices_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_copy_input_device_info_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_get_output_devices_count(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_copy_output_device_info_by_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_query_input_devices(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_query_output_devices(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_set_input_device_settings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_set_output_device_settings(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_add_notify_participant_updated(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_remove_notify_participant_updated(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_add_notify_audio_devices_changed(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_remove_notify_audio_devices_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_add_notify_audio_input_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_remove_notify_audio_input_state(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_add_notify_audio_output_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__eos_rtc_audio_remove_notify_audio_output_state(char* __arg_buffer, double __arg_buffer_length);

