
EpicGames_P2P_RemoveNotifyIncomingPacketQueueFull(notifyIncomingPacketQueueFull)
EpicGames_P2P_RemoveNotifyPeerConnectionClosed(notifyPeerConnectionClosed)
EpicGames_P2P_RemoveNotifyPeerConnectionEstablished(notifyPeerConnectionEstablished)
EpicGames_P2P_RemoveNotifyPeerConnectionInterrupted(notifyPeerConnectionInterrupted)
EpicGames_P2P_RemoveNotifyPeerConnectionRequest(notifyPeerConnectionRequest)

show_debug_message("CLEAN UP")
for(var a = 0 ; a < array_length(EstablishedProductIDs) ; a++)
{
	disconnect(EstablishedProductIDs[a])
}
